version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --output-template-file lambdaoutput.yaml --s3-bucket hollers-artifacts-bucket-gl

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml