version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      # This command finds requirements.txt and installs dependencies
      - sam build --template-file pdftotxt.yaml
      # This command packages the built artifacts for deployment
      - sam package --output-template-file lambdaoutput.yaml --s3-bucket hollers-artifacts-bucket-gl

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml